spring: 
  profiles: 
    active: dev
    
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/alala?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100     #连接数据库的数据量
        max-idle: 10        #等待连接中的数量
        max-wait: 100000    #等待连接时间
      timeout: 5000         #连接超时时间


eureka:
  client:
    #表示是否将自己注册进EurekaService 默认为true
    register-with-eureka: true
    #是否从EurekaService中抓取已有的注册信息，默认为false。单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka     #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka     #集群版

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  
